# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cap.trade.duration.interface <- function(indicatorIn, shortMinCap, longMinCap, shortMaxCap, longMaxCap, waitNewSignal) {
    .Call('btutils_capTradeDurationInterface', PACKAGE = 'btutils', indicatorIn, shortMinCap, longMinCap, shortMaxCap, longMaxCap, waitNewSignal)
}

construct.indicator.interface <- function(longEntriesIn, longExitsIn, shortEntriesIn, shortExitsIn) {
    .Call('btutils_constructIndicatorInterface', PACKAGE = 'btutils', longEntriesIn, longExitsIn, shortEntriesIn, shortExitsIn)
}

indicator.from.trendline.interface <- function(trendlineIn, thresholdsIn) {
    .Call('btutils_indicatorFromTrendlineInterface', PACKAGE = 'btutils', trendlineIn, thresholdsIn)
}

zig.zag.interface <- function(pricesIn, changesIn, percent) {
    .Call('btutils_zigZagInterface', PACKAGE = 'btutils', pricesIn, changesIn, percent)
}

process.trade.interface <- function(opIn, hiIn, loIn, clIn, ibeg, iend, pos, stopLoss, stopTrailing, profitTarget, maxDays, tickSize) {
    .Call('btutils_processTradeInterface', PACKAGE = 'btutils', opIn, hiIn, loIn, clIn, ibeg, iend, pos, stopLoss, stopTrailing, profitTarget, maxDays, tickSize)
}

process.trades.interface <- function(ohlcIn, ibegsIn, iendsIn, positionIn, stopLossIn, stopTrailingIn, profitTargetIn, maxDaysIn, tickSize) {
    .Call('btutils_processTradesInterface', PACKAGE = 'btutils', ohlcIn, ibegsIn, iendsIn, positionIn, stopLossIn, stopTrailingIn, profitTargetIn, maxDaysIn, tickSize)
}

trades.from.indicator.interface <- function(indicatorIn) {
    .Call('btutils_tradesFromIndicatorInterface', PACKAGE = 'btutils', indicatorIn)
}

calculate.returns.interface <- function(clIn, ibegIn, iendIn, positionIn, exitPriceIn, inDollars) {
    .Call('btutils_calculateReturnsInterface', PACKAGE = 'btutils', clIn, ibegIn, iendIn, positionIn, exitPriceIn, inDollars)
}

locf.interface <- function(vin, value) {
    .Call('btutils_locfInterface', PACKAGE = 'btutils', vin, value)
}

leading.nas.interface <- function(vin) {
    .Call('btutils_leadingNAs', PACKAGE = 'btutils', vin)
}

laguerre.filter.interface <- function(vin, gamma) {
    .Call('btutils_laguerreFilterInterface', PACKAGE = 'btutils', vin, gamma)
}

laguerre.rsi.interface <- function(vin, gamma) {
    .Call('btutils_laguerreRSIInterface', PACKAGE = 'btutils', vin, gamma)
}

